// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.DAL.EF;

namespace WebApi.DAL.Migrations.MaterialDb
{
    [DbContext(typeof(MaterialDbContext))]
    partial class MaterialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MaterialVersionUserMaterialVersion", b =>
                {
                    b.Property<string>("MaterialVersionsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwningUsersUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaterialVersionsId", "OwningUsersUserId");

                    b.HasIndex("OwningUsersUserId");

                    b.ToTable("MaterialVersionUserMaterialVersion");
                });

            modelBuilder.Entity("WebApi.DAL.Entities.Material.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ActualVersionNum")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WebApi.DAL.Entities.Material.MaterialVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialVersions");
                });

            modelBuilder.Entity("WebApi.DAL.Entities.Material.UserMaterialVersion", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.ToTable("UserMaterialVersions");
                });

            modelBuilder.Entity("MaterialVersionUserMaterialVersion", b =>
                {
                    b.HasOne("WebApi.DAL.Entities.Material.MaterialVersion", null)
                        .WithMany()
                        .HasForeignKey("MaterialVersionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.DAL.Entities.Material.UserMaterialVersion", null)
                        .WithMany()
                        .HasForeignKey("OwningUsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApi.DAL.Entities.Material.MaterialVersion", b =>
                {
                    b.HasOne("WebApi.DAL.Entities.Material.Material", "Material")
                        .WithMany("Versions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("WebApi.DAL.Entities.Material.Material", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
